### ISSUE TITLE
Handlebars unintentionally parsing twig variables

### ISSUE THREAD

**Issue by bchiang7** [gvjacob/temples#3]
Hey @gvjacob! I recently added this package to a [puppy](https://github.com/Upstatement/puppy) project that uses Twig, and I realized that Handlebars parses twig variables that I want to persist into the output file. Below is a pared down example:

## In `.temples.yaml`

```yaml
Component Page:
  temples:
    - template: ./temples/component-page.hbs
      output: ./src/pages/components/{{ kebab name }}.html
  prompt:
    - key: name
      doc: Component name (title case)
```

## In `./temples/component-page.hbs`

```twig
---
title: {{ name }}
---

{% extends "@templates/layouts/styleguide.twig" %}

{% block content %}

{% set htmlContent %}
{% include "@components/{{ kebab name }}.twig" %}
{% endset %}

<section class="styleguide__rendered">
  {{ htmlContent }}
</section>

{% endblock %}

```

## Output HTML file

```html
---
title: Test Component
---

<!-- Don't forget to add this page to src/data/sidebar.json! -->

{% extends "@templates/layouts/styleguide.twig" %}

{% block content %}

{% set htmlContent %}
{% include "@components/test-component.twig" %}
{% endset %}

<section class="styleguide__rendered">
  
</section>

{% endblock %}

```

## Expected Behavior

I expected `{{ htmlContent }}` to carry over within the `<section>` tag into my output file. It's probably disappearing because Handlebars doesn't recognize it as a defined variable. 

I tried using "triple-stash" (`{{{ htmlContent }}}`) in order to escape the handlebars curly braces as suggested by [this stack overflow thread](https://stackoverflow.com/questions/23656516/handlebars-escape-string), but no dice. Any ideas on how to fix this?
