### ISSUE TITLE
Special characters are being converted into HTML entities

### ISSUE THREAD

**Issue by bchiang7** [gvjacob/temples#4]
Handlebars seems to be converting special characters into HTML entities.

# Steps to reproduce

```yaml
# temples.yaml

generators:
  test:
    files:
      - template: ./templates/test.hbs
        target: ./src/{{ filename }}.md
    props:
      - name: name
      - name: filename
```

```hbs
<!-- ./templates/test.hbs -->
---
title: {{ name }}
---

TK
```

## Props passed to CLI

`name`:  `People's Party`
`filename`:  `people's&`

## Output

filename: `people&#x27;s&amp;.md`

file contents:

```md
---
title: People&#x27;s Party
---

TK
```
